# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262ce4cf2b746c9fce3956aeec58ae35ae83dd1102b9489b09fddd9ad243321e05e25a8705e00ebed0845c5854ef8f9ff35b19d2e0ca1bddc0077a27fdb8cd76

test:
  secret_key_base: f551a743b2435924e9af9e5bacd0a76563d572516c65f36abdfbc37d040c2039b42a5480568bbaaa234d3c897693e2e08dff3fc6cda587fe0956792bbd5f1d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
